/**
 * Global axios instance for all API calls. 
 * Attaches the JWT to every request and handles 401 (expired) redirects.
 */
import axios from 'axios';


// All requests go through Vite proxy → https://localhost:3443
const api = axios.create({ baseURL: '/' });

// Attach JWT to every request automatically
api.interceptors.request.use((config) => {
  const token = sessionStorage.getItem('kc_token');
  if (token) config.headers.Authorization = `Bearer ${token}`;
  return config;
});

// Auto-logout on 401
api.interceptors.response.use(
  (res) => res,
  (err) => {
    if (err.response?.status === 401) {
      sessionStorage.removeItem('kc_token');
      window.location.href = '/';
    }
    return Promise.reject(err);
  }
);

// ─── Auth ─────────────────────────────────────────────────────────────────────
// Authenticates a user and returns a session token and user profile.
export const login = (username, password) =>
  api.post('/auth/login', { username, password }).then((r) => r.data);

// Creates a new user account with the provided credentials.
export const register = (username, password) =>
  api.post('/auth/register', { username, password }).then((r) => r.data);

// Fetches the current user's profile information based on their session token.
export const getMe = () => api.get('/auth/me').then((r) => r.data);

// ─── Highlights ───────────────────────────────────────────────────────────────
// Retrieves a list of approved highlights, optionally filtered by competition or team.
export const getHighlights = (filters = {}) =>
  api.get('/highlights', { params: filters }).then((r) => r.data);

// Returns the top highlights ranked by user likes.
export const getTrendingHighlights = () =>
  api.get('/highlights/trending').then((r) => r.data);

// Returns a list of highlights awaiting administrative approval.
export const getPendingHighlights = () =>
  api.get('/highlights/pending').then((r) => r.data);

// Submits a new highlight with video and thumbnail files via multi-part form data.
export const uploadHighlight = (formData) =>
  api.post('/highlights', formData, {
    headers: { 'Content-Type': 'multipart/form-data' },
  }).then((r) => r.data);

// Toggles the 'like' status of a highlight for the current user.
export const likeHighlight = (id) =>
  api.post(`/highlights/${id}/like`).then((r) => r.data);

// Promotes a pending highlight to 'approved' status, making it public.
export const approveHighlight = (id) =>
  api.patch(`/highlights/${id}/approve`).then((r) => r.data);

// Permanently deletes a highlight and its associated files.
export const deleteHighlight = (id) =>
  api.delete(`/highlights/${id}`).then((r) => r.data);

// ─── Chat ─────────────────────────────────────────────────────────────────────
// Fetches the message history for a specific chat channel.
export const getChatMessages = (channel = 'general') =>
  api.get('/chat/messages', { params: { channel } }).then((r) => r.data);

// Retrieves the list of all available chat channels.
export const getChannels = () =>
  api.get('/chat/channels').then((r) => r.data);

// Creates a new custom chat channel.
export const createChannel = (data) =>
  api.post('/chat/channels', data).then((r) => r.data);

// Removes a specific chat channel and all its messages.
export const deleteChannel = (id) =>
  api.delete(`/chat/channels/${id}`).then((r) => r.data);

// ─── Widgets ──────────────────────────────────────────────────────────────────
// Fetches a random football fact generated by the AI.
export const getAIFact = () =>
  api.get('/widgets/fact').then((r) => r.data);

export default api;
